#@data/values
---
port: 5000

env:
  - name: PORT
    value: "5000"
  - name: TZ
    value: America/Sao_Paulo

ingress:
  enable: true
  type: nginx
  domain:
    enable: true
    name: forattini.app
    email: filipeforattini1@gmail.com
